default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  database: gpr_bank

development:
  <<: *default
  database: gpr_bank_dev

test:
  <<: *default
  database: gpr_bank_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
